# Generated by Django 5.2 on 2025-09-09 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_userfriend_status'),
        ('user_channel', '0003_userchannel_is_direct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='메시지 내용 html 형식')),
                ('clean_content', models.TextField(help_text='메시지 내용 텍스트 형식')),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('system', 'System'), ('bot', 'Bot')], default='normal', help_text='메시지 유형', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='메시지 상태', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='메시지 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='메시지 수정일')),
                ('channel', models.ForeignKey(blank=True, help_text='채널', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_channel.userchannel')),
                ('from_user', models.ForeignKey(help_text='메시지 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user.usermain')),
                ('root_message', models.ForeignKey(blank=True, help_text='스레드 루트 메시지', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_replies', to='message.message')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], help_text='첨부 유형', max_length=20)),
                ('url', models.URLField(help_text='파일 URL (S3)')),
                ('name', models.CharField(blank=True, help_text='파일 이름', max_length=255, null=True)),
                ('size', models.BigIntegerField(blank=True, help_text='파일 크기 (byte 단위)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(help_text='첨부된 메시지', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='message.message')),
            ],
            options={
                'db_table': 'message_attachment',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'created_at'], name='message_channel_ab1201_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_user'], name='message_from_us_a105a9_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='message_att_message_305b6a_idx'),
        ),
    ]
