# Generated by Django 5.2 on 2025-09-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
