# Generated by Django 5.2 on 2025-09-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='messageattachment',
            name='message_att_message_305b6a_idx',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(blank=True, help_text='첨부 파일', related_name='messages', to='message.messageattachment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('system', 'System'), ('file', 'File'), ('bot', 'Bot')], default='normal', help_text='메시지 유형', max_length=10),
        ),
    ]
