# Generated by Django 5.2 on 2025-05-05 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0004_alter_userfriend_from_user_alter_userfriend_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="채널 이름", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="채널 설명", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="채널 생성자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.usermain",
                    ),
                ),
            ],
            options={
                "db_table": "user_channel",
            },
        ),
        migrations.CreateModel(
            name="UserChannelMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="참여일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="채널 참여 관계",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_memberships",
                        to="user_channel.userchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자 채널 참여 관계",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="user.usermain",
                    ),
                ),
            ],
            options={
                "db_table": "user_channel_member",
                "unique_together": {("channel", "user")},
            },
        ),
        migrations.AddField(
            model_name="userchannel",
            name="members",
            field=models.ManyToManyField(
                help_text="참여 사용자",
                related_name="channels",
                through="user_channel.UserChannelMember",
                to="user.usermain",
            ),
        ),
    ]
