# Generated by Django 5.2 on 2025-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='is_private',
            field=models.BooleanField(default=False, help_text='채널 공개 여부'),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='type',
            field=models.CharField(blank=True, help_text='채널 유형', max_length=10, null=True),
        ),
    ]
