# Generated by Django 5.2 on 2025-09-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_channel', '0002_userchannel_is_private_userchannel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='is_direct',
            field=models.BooleanField(default=False, help_text='다이렉트 메시지 채팅 여부'),
        ),
    ]
