"""
Django settings for rtc_django_chat project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import json
import logging

logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 환경변수 로드
def get_env(env_file="local.env"):
    env_path = os.path.join(BASE_DIR, env_file)
    try:
        with open(env_path, "r") as f:
            env_data = json.load(f)
        return env_data
    except Exception as e:
        logger.error(f"Error loading {env_file}: {e}")
        return {}


environ = get_env()


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$+*2=0jygrs^th_^8xy=4glq8(ib__=(io7e7(tx&3)n40y(y!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Stop Django from redirecting URLs that don't end with a slash
APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "user",
    "user_channel",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "common.middlewares.cookie_jwt.CookieJWTAuthentication",
]

PRODUCTION = environ.get("PRODUCTION")

JWT_SECRET_KEY = environ.get("JWT_SECRET_KEY")
JWT_ALGORITHM = "HS256"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ALGORITHM": JWT_ALGORITHM,
    "SIGNING_KEY": JWT_SECRET_KEY,
}

ROOT_URLCONF = "rtc_django_chat.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rtc_django_chat.wsgi.application"

CASSANDRA_KEYSPACE = environ.get("CASSANDRA_KEYSPACE")
CASSANDRA_HOST = environ.get("CASSANDRA_HOST")
CASSANDRA_PORT = environ.get("CASSANDRA_PORT")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": environ.get("POSTGRES_DATABASE_NAME"),
        "USER": environ.get("POSTGRES_DATABASE_USER"),
        "PASSWORD": environ.get("POSTGRES_DATABASE_PASSWORD"),
        "HOST": environ.get("POSTGRES_DATABASE_HOST"),
        "PORT": environ.get("POSTGRES_DATABASE_PORT"),
    },
    "cassandra": {
        "ENGINE": "django_cassandra_engine",
        "NAME": CASSANDRA_KEYSPACE,
        "HOST": CASSANDRA_HOST,
        "PORT": CASSANDRA_PORT,
    },
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FRONTEND_URL = environ.get("FRONTEND_URL")
