# Generated by Django 5.2 on 2025-05-03 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="사용자 이름", max_length=255, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="로그인 이메일", max_length=254, unique=True
                    ),
                ),
                ("password", models.CharField(help_text="비밀번호", max_length=255)),
                (
                    "refresh_token",
                    models.CharField(help_text="마지막 리프레시 토큰", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
            ],
            options={
                "db_table": "user_main",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, help_text="프로필 이미지", max_length=255, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="user.usermain"
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
    ]
