# Generated by Django 5.2 on 2025-05-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermain",
            name="refresh_token",
            field=models.CharField(
                blank=True, help_text="마지막 리프레시 토큰", max_length=255, null=True
            ),
        ),
    ]
