# Generated by Django 5.2 on 2025-05-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_usermain_refresh_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFriend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_created",
                        to="user.usermain",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_received",
                        to="user.usermain",
                    ),
                ),
            ],
            options={
                "db_table": "user_friend",
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.AddField(
            model_name="usermain",
            name="friends",
            field=models.ManyToManyField(
                related_name="friend_of", through="user.UserFriend", to="user.usermain"
            ),
        ),
    ]
