# Generated by Django 5.2 on 2025-05-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_userfriend_usermain_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfriend",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_friend",
                to="user.usermain",
            ),
        ),
        migrations.AlterField(
            model_name="userfriend",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friend",
                to="user.usermain",
            ),
        ),
    ]
