# Generated by Django 5.2 on 2025-05-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_userfriend_from_user_alter_userfriend_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfriend",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="친구 상태",
                max_length=255,
            ),
        ),
    ]
